@startuml

title Diagrama de Secuencia: C-03 Importar datos masivamente (Alt: CSV con errores)

skinparam style strictuml
skinparam ParticipantPadding 30
skinparam BoxPadding 12

autonumber

actor Administrador
participant "Sistema\n(EstructuraPage)" as Interfaz
participant "csvParser"                 as Parser
   



Administrador -> Interfaz: Ingresa a estructura academica
activate Interfaz
Interfaz --> Administrador: Se muestran entidades y botones
deactivate Interfaz

Administrador -> Interfaz: Hace click en "Importar CSV"
activate Interfaz
Interfaz --> Administrador: Abre explorador de archivos
deactivate Interfaz

Administrador -> Interfaz: Selecciona archivo CSV
activate Interfaz

Interfaz -> Parser: validarFormatoArchivo(archivo)
activate Parser
Parser --> Interfaz: Formato de archivo validado
deactivate Parser

Interfaz -> Parser: parsearCSV(archivo)
activate Parser
Parser --> Interfaz: Devuelve array de filas
deactivate Parser

Interfaz -> Parser: validarEsquema(filas)
activate Parser
Parser --> Interfaz: Esquema validado
deactivate Parser

Interfaz -> Parser: detectarDuplicados(filas)
activate Parser
Parser --> Interfaz: Se detectaron duplicados
deactivate Parser

note right of Interfaz
  El sistema detecta datos
  duplicados ANTES de invocar
  al backend. 
end note

Interfaz --> Administrador: "Se encontraron datos duplicados, por favor verifique el archivo"
deactivate Interfaz


@enduml
