@startuml

title Diagrama de Secuencia: C-03 Importar datos masivamente (Caso Normal)

skinparam style strictuml
skinparam ParticipantPadding 30
skinparam BoxPadding 12

autonumber

actor Administrador
participant "Sistema\n(EstructuraPage)" as Interfaz
participant "csvParser"                 as Parser
participant "Edificio"
participant "Facultad"
participant "Carrera"
participant "Periodo"
participant "Asignatura"       
participant "Profesor" 
participant "Comision"        



Administrador -> Interfaz: Ingresa a estructura academica
activate Interfaz
Interfaz --> Administrador: Se muestran entidades y botones
deactivate Interfaz

Administrador -> Interfaz: Hace click en "Importar CSV"
activate Interfaz
Interfaz --> Administrador: Abre explorador de archivos
deactivate Interfaz

Administrador -> Interfaz: Selecciona archivo CSV
activate Interfaz

Interfaz -> Parser: validarFormatoArchivo(archivo)
activate Parser
Parser --> Interfaz: Formato de archivo validado
deactivate Parser

Interfaz -> Parser: parsearCSV(archivo)
activate Parser
Parser --> Interfaz: Devuelve array de filas
deactivate Parser

Interfaz -> Parser: validarEsquema(filas)
activate Parser
Parser --> Interfaz: Esquema validado
deactivate Parser

Interfaz -> Parser: detectarDuplicados(filas)
activate Parser
Parser --> Interfaz: No se detectaron duplicados
deactivate Parser

Interfaz -> Parser: detectarIncompletos(filas)
activate Parser
Parser --> Interfaz: No se detectaron campos incompletos
deactivate Parser

Interfaz -> Parser: detectarFormatosInvalidos(filas)
activate Parser
Parser --> Interfaz: No se detectaron formatos invalidos
deactivate Parser
Interfaz -> Edificio: Solicita crear Edificio/s
activate Edificio
Edificio -> Edificio: insertar(filas)
Edificio --> Interfaz: Edificio/s insertado 
deactivate Edificio
Interfaz -> Facultad: Solicita crear Facultad/es
activate Facultad
Facultad -> Facultad: insertar(filas)
Facultad --> Interfaz: Facultad/es insertada/s
deactivate Facultad
Interfaz -> Carrera: Solicita crear Carrera/s
activate Carrera
Carrera -> Carrera: insertar(filas)
Carrera --> Interfaz: Carrera/s insertada/s
deactivate Carrera
Interfaz -> Periodo: Solicita crear Periodo/s
activate Periodo
Periodo -> Periodo: insertar(filas)
Periodo --> Interfaz: Periodo/s insertado/s
deactivate Periodo
Interfaz -> Asignatura: Solicita crear Asignatura/s
activate Asignatura
Asignatura -> Asignatura: insertar(filas)
Asignatura --> Interfaz: Asignatura/s insertada/s
deactivate Asignatura
Interfaz -> Profesor: Solicita crear Profesor/es
activate Profesor
Profesor -> Profesor: insertar(filas)
Profesor --> Interfaz: Profesor/es insertado/s
deactivate Profesor
Interfaz -> Comision: Solicita crear Comision/es
activate Comision
Comision -> Comision: insertar(filas)
Comision --> Interfaz: Comision/es insertada/s
deactivate Comision

Interfaz --> Administrador: "Archivo importado con exito"
deactivate Interfaz

@enduml
