@startuml

title Diagrama de Secuencia: C-01 Gestionar Reportes y Resolucion de Conflictos (Caso Normal)

skinparam style strictuml
skinparam ParticipantPadding 40
skinparam BoxPadding 20

autonumber

actor Administrador

participant "Sistema\n(Interfaz)"        as Interfaz
participant "Reporte"                    as R
participant "Usuario"                    as U
participant "AuditoriaAdministrativa"    as A
participant "Notificacion"               as N

Administrador -> Interfaz: Ingresa al panel de reportes
activate Interfaz

Interfaz -> R: Solicita lista de Reportes
activate R
R -> R: obtenerReportes()
Interfaz <-- R: Devuelve lista de Reportes
deactivate R

Interfaz --> Administrador: Se muestra lista y opciones de filtrado
deactivate Interfaz

Administrador -> Interfaz: Selecciona filtro "Pendiente"
activate Interfaz

Interfaz -> R: Solicita lista de Reportes filtrada
activate R
R -> R: obtenerReportesFiltrados("Pendiente")
Interfaz <-- R: Devuelve lista de Reportes filtrada
deactivate R

Interfaz --> Administrador: Se muestra lista filtrada
deactivate Interfaz

Administrador -> Interfaz: Hace click en un reporte
activate Interfaz

Interfaz -> R: Solicita detalles del Reporte
activate R
R -> R: obtenerDetalleReporte(id_reporte)
Interfaz <-- R: Devuelve detalles del Reporte
deactivate R

Interfaz --> Administrador: Se muestra detalle del Reporte completo
deactivate Interfaz

Administrador -> Interfaz: Selecciona accion y fecha de suspension
activate Interfaz

Interfaz -> R: Solicita actualizacion del Reporte
activate R
R -> R: actualizarEstado(id_reporte, "Resuelto", resolucion)
Interfaz <-- R: Estado del reporte actualizado
deactivate R

Interfaz -> U: Solicita actualizar la fecha de suspension
activate U
U -> U: actualizarFechaSuspension(receptor_id, duracion)
Interfaz <-- U: Fecha de suspension registrada
deactivate U


Interfaz -> A: Solicita registrar la Auditoria
activate A
A -> A: registrar(id_reporte, accion, admin_id)
Interfaz <-- A: Auditoria registrada
deactivate A

Interfaz -> N: Solicita crear la Notificacion
activate N
N -> N: crearNotificacion(receptor_id, accion, mensaje, fecha)
Interfaz <-- N: Notificacion creada
deactivate N

Interfaz -> N: Solicita enviar la Notificacion
activate N
N -> N: notificar(emisor_id, receptor_id)
Interfaz <-- N: Notificacion enviada
deactivate N

Interfaz --> Administrador: "Reporte actualizado"
deactivate Interfaz

@enduml