@startuml

title Diagrama de Secuencia: C-01 Gestionar Reportes (Alt: Reporte ya procesado)

skinparam style strictuml
skinparam ParticipantPadding 40
skinparam BoxPadding 20

autonumber

actor Administrador

participant "Sistema\n(Interfaz)" as Interfaz
participant "Reporte"             as R

Administrador -> Interfaz: ingresa al panel de reportes
activate Interfaz

Interfaz -> R: Solicita lista de reportes
activate R
    R -> R: obtenerReportes()
Interfaz <-- R: Devuelve lista de reportes
deactivate R

Interfaz --> Administrador: Se muestra lista y opciones de filtrado
deactivate Interfaz

Administrador -> Interfaz: Selecciona filtro "Pendiente"
activate Interfaz

Interfaz -> R: Solicita reportes filtrados por estado
activate R
    R -> R: obtenerReportesFiltrados("Pendiente")
Interfaz <-- R: Devuelve los reportes filtrados
deactivate R

Interfaz --> Administrador: Se muestra lista filtrada
deactivate Interfaz

Administrador -> Interfaz: Hace click en un reporte
activate Interfaz

Interfaz -> R: Solicita detalle del reporte
activate R
R -> R: obtenerDetalleReporte(id_reporte)

note right of R
  El sistema detecta que el
  reporte ya no esta pendiente
end note

Interfaz <-- R: Devuelve error de Reporte ya gestionado
deactivate R

Interfaz --> Administrador: "Reporte ya gestionado"
deactivate Interfaz

@enduml