@startuml

title Diagrama de Secuencia: C-02 Crear Comision (Caso Normal)

skinparam style strictuml
skinparam ParticipantPadding 40
skinparam BoxPadding 20

autonumber

actor Administrador

participant "Sistema\n(Interfaz)" as Interfaz
participant "Asignatura" as AS
participant "Profesor"   as P
participant "Comision"   as C


Administrador -> Interfaz: Ingresa a estructura academica
activate Interfaz
Interfaz --> Administrador: Se muestran entidades existentes
deactivate Interfaz
Administrador -> Interfaz: Hace click en "Comisiones"
activate Interfaz
Interfaz -> C: Solicita lista de Comisiones
activate C
C -> C: obtenerComisiones()
Interfaz <-- C: Devuelve lista de Comisiones
deactivate C

Interfaz --> Administrador: Se muestra listado y botones
deactivate Interfaz

Administrador -> Interfaz: Hace click en "Crear Comision"
activate Interfaz
Interfaz --> Administrador: Se muestra addComisionModal
deactivate Interfaz

Administrador -> Interfaz: Completa campos y confirma
activate Interfaz

' Auto-llamada en Interfaz
Interfaz -> Interfaz: validarCampos()

' Interacción con Asignatura
Interfaz -> AS: Solicita verificacion de id_asignatura
activate AS
    AS -> AS: verificarExistencia(id_asignatura)

Interfaz <-- AS: Confirma existencia
deactivate AS

' Interacción con Comision
Interfaz -> C: Solicita creacion de la comision
activate C
    C -> C: crear(nombre, letraDesde, letraHasta, id_asignatura)
Interfaz <-- C: Comision creada
deactivate C
Interfaz -> P: Solicita asignaciones
activate P
P -> P: asignar(id_comision, profesores_ids)
Interfaz <-- P: Asignaciones creadas
deactivate P

deactivate C

Interfaz --> Administrador: "Comision creada con exito"
deactivate Interfaz

@enduml