
@startuml

title Diagrama de Secuencia: C-01 Gestionar Denuncia (Caso Normal)

skinparam style strictuml
skinparam ParticipantPadding 30
skinparam BoxPadding 12

autonumber

actor Administrador
participant "Sistema\n(DenunciasPage)" as Interfaz
participant "Denuncia"                   as Denuncia


Administrador -> Interfaz: Ingresa al panel administrativo y hace click en "Denuncias"
activate Interfaz
Interfaz -> Denuncia: obtenerDenuncias()
activate Denuncia
Denuncia --> Interfaz: Devuelve lista de Denuncias
deactivate Denuncia
Interfaz --> Administrador: Muestra listado de Denuncias
deactivate Interfaz
Administrador -> Interfaz: Hace click en "Abrir" de un Denuncia
activate Interfaz
Interfaz -> Denuncia: Solicita detalle del Denuncia
activate Denuncia
Denuncia -> Denuncia: obtenerDetalleDenuncia(id_denuncia)
Denuncia --> Interfaz: Devuelve detalle del Denuncia
deactivate Denuncia
Interfaz -> Interfaz: setIsDenunciaModalOpen(true)
Interfaz --> Administrador: Muestra modal para resolver el Denuncia
deactivate Interfaz
Administrador -> Interfaz: Selecciona acción y hace click en "Confirmar"
activate Interfaz
Interfaz -> Denuncia: Solicita resolver Denuncia
activate Denuncia
Denuncia -> Denuncia: resolverDenuncia(id_denuncia, {estado, accion, fechaHasta, observaciones, admin_id})
Denuncia --> Interfaz: Denuncia resuelto
deactivate Denuncia
Interfaz --> Administrador: "Denuncia resuelto con éxito. Se ha notificado a los usuarios"

deactivate Interfaz

@enduml